### ISSUE TITLE
Crashing with no model_cls on custom L with custom schema

### ISSUE THREAD

**Issue by thaelathy** [CodeTeam/tcrudge#6]
One needs to define a model_cls, even if there's no need.

For example - "changelog" and it's incidents handler.
You defined a logic of GET, schema defined, too.
Defined that there's no POST, PUT, PATCH, DELETE for the handler.
So I expect, that I don't need to define a model_cls.
Mb I use two classes? Or mb I defined schema myself and don't want anyone to generate it?

**Comment by juntatalor** [comment]
Hi, @thaelathy !
You can use BaseHandler (https://github.com/CodeTeam/tcrudge/blob/master/tcrudge/handlers.py#L17) for this purpose.
